theme: jekyll-theme-cayman
title: Advanced Search & Bulk Actions
description: Help documentation for the Advanced Search & Bulk Actions Zendesk app
show_downloads: false
github:
  is_project_page: false
